name: thread_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_toast_message_bar: ^0.0.8
  fluttertoast: ^8.2.4
  font_awesome_flutter: ^10.6.0
  google_fonts: ^6.1.0
  image_picker: ^1.0.5
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
